{% set commit = "b3a2159b7e6950726157626069c30712427d55b2" %}
{% set version = "0.3.0.430.gb3a2159" %}

package:
  name: symengine
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/symengine/symengine/archive/{{ commit }}.tar.gz

build:
  number: 1
  msvc_compiler: 14.0
  features:
    - vc14             # [win]

requirements:
  build:
    - toolchain        # [unix]
    - cmake
    - gmp 6.1.*        # [unix]
    - mpir 3.*         # [win]
    - mpfr 4.*
    - mpc 1.*
    - vc 14            # [win]
    - llvmdev 3.9.*    # [not win32]
    - libflint 2.5.*   # [unix]
  run:
    - gmp >=6.1,<7     # [unix]
    - mpir 3.*         # [win]
    - mpfr 4.*
    - mpc 1.*
    - vc 14            # [win]
    - libflint 2.5.*   # [unix]

test:
  commands:
    - if not exist %LIBRARY_INC%\\symengine\\basic.h exit 1     # [win]
    - if not exist %LIBRARY_LIB%\\symengine.lib exit 1          # [win]
    - if not exist %LIBRARY_BIN%\\symengine.dll exit 1          # [win]
    - test -f $PREFIX/include/symengine/basic.h                 # [unix]
    - test -f $PREFIX/lib/libsymengine.so                       # [linux]
    - test -f $PREFIX/lib/libsymengine.dylib                    # [osx]

about:
  home: https://github.com/symengine/symengine
  license: MIT
  license_file: LICENSE
  summary: 'SymEngine is a fast symbolic manipulation library, written in C++'

extra:
  recipe-maintainers:
    - isuruf
    - certik
